"""Application-owned persistence boundaries for V1-C03."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, Sequence

from strategic_intelligence.domain.models import (
    Case, Claim, ClaimEvidenceLink, Evidence, FollowUpResearchAttempt, GovernanceDecision, Source, WorkflowRun, WorkflowStage,
)


@dataclass(frozen=True)
class ArtifactReference:
    case_id: str
    run_id: str
    artifact_id: str
    suffix: str


class ArtifactStore(Protocol):
    def write(self, case_id: str, run_id: str, content: bytes, suffix: str = ".bin") -> ArtifactReference: ...
    def read(self, reference: ArtifactReference) -> bytes: ...
    def delete_case(self, case_id: str) -> None: ...


class PersistenceRepository(Protocol):
    def create_case(self, case: Case) -> Case: ...
    def get_case(self, case_id: str) -> Case | None: ...
    def update_case(self, case: Case) -> Case: ...
    def save_workflow_run(self, run: WorkflowRun) -> WorkflowRun: ...
    def get_workflow_run(self, run_id: str) -> WorkflowRun | None: ...
    def save_source(self, source: Source) -> Source: ...
    def get_source(self, source_id: str) -> Source | None: ...
    def save_evidence(self, evidence: Evidence) -> Evidence: ...
    def get_evidence(self, evidence_id: str) -> Evidence | None: ...
    def save_claim_with_links(self, claim: Claim, links: Sequence[ClaimEvidenceLink]) -> Claim: ...
    def get_claim(self, claim_id: str) -> Claim | None: ...
    def get_claim_evidence_links(self, claim_id: str) -> list[ClaimEvidenceLink]: ...
    def append_claim_evidence(self, claim_id: str, evidence: Sequence[Evidence], links: Sequence[ClaimEvidenceLink]) -> Claim: ...
    def save_follow_up_attempt(self, attempt: FollowUpResearchAttempt) -> FollowUpResearchAttempt: ...
    def list_follow_up_attempts(self, claim_id: str) -> list[FollowUpResearchAttempt]: ...
    def save_governance_decision(self, decision: GovernanceDecision) -> GovernanceDecision: ...
    def list_governance_decisions(self, target_id: str) -> list[GovernanceDecision]: ...
    def accept_checkpoint(self, run_id: str, stage: WorkflowStage, required_records: Sequence[tuple[str, str]]) -> None: ...
