"""Application-owned persistence boundaries for V1-C03."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, Sequence

from strategic_intelligence.domain.models import (
    AuditEvent, Case, Claim, ClaimEvidenceLink, EntityRecord, Evidence, FollowUpResearchAttempt, GovernanceDecision, GraphNode, RelationshipRecord, Source, TrackedCompany, WorkflowRun, WorkflowStage,
)


@dataclass(frozen=True)
class ArtifactReference:
    case_id: str
    run_id: str
    artifact_id: str
    suffix: str


class ArtifactStore(Protocol):
    def write(self, case_id: str, run_id: str, content: bytes, suffix: str = ".bin") -> ArtifactReference: ...
    def read(self, reference: ArtifactReference) -> bytes: ...
    def delete_case(self, case_id: str) -> None: ...


class PersistenceRepository(Protocol):
    def create_case(self, case: Case) -> Case: ...
    def get_case(self, case_id: str) -> Case | None: ...
    def update_case(self, case: Case) -> Case: ...
    def save_workflow_run(self, run: WorkflowRun) -> WorkflowRun: ...
    def get_workflow_run(self, run_id: str) -> WorkflowRun | None: ...
    def save_tracked_company(self, company: TrackedCompany) -> TrackedCompany: ...
    def get_tracked_company(self, tracked_company_id: str) -> TrackedCompany | None: ...
    def get_tracked_company_by_normalized_name(self, normalized_name: str) -> TrackedCompany | None: ...
    def list_tracked_companies(self) -> list[TrackedCompany]: ...
    def save_entity(self, entity: EntityRecord) -> EntityRecord: ...
    def get_entity(self, entity_id: str) -> EntityRecord | None: ...
    def find_entities(self, entity_type: str, normalized_name: str, context_key: str | None = None) -> list[EntityRecord]: ...
    def list_entities(self) -> list[EntityRecord]: ...
    def save_graph_node(self, node: GraphNode) -> GraphNode: ...
    def get_graph_node(self, entity_id: str) -> GraphNode | None: ...
    def list_graph_nodes(self) -> list[GraphNode]: ...
    def save_graph_edge(self, relationship: RelationshipRecord, canonical_key: str) -> RelationshipRecord: ...
    def get_graph_edge(self, relationship_id: str) -> RelationshipRecord | None: ...
    def list_graph_edges(self) -> list[RelationshipRecord]: ...
    def graph_edge_exists_by_key(self, canonical_key: str) -> bool: ...
    def save_audit_event(self, event: AuditEvent) -> AuditEvent: ...
    def list_audit_events(self, run_id: str) -> list[AuditEvent]: ...
    def save_source(self, source: Source) -> Source: ...
    def get_source(self, source_id: str) -> Source | None: ...
    def save_evidence(self, evidence: Evidence) -> Evidence: ...
    def get_evidence(self, evidence_id: str) -> Evidence | None: ...
    def save_claim_with_links(self, claim: Claim, links: Sequence[ClaimEvidenceLink]) -> Claim: ...
    def get_claim(self, claim_id: str) -> Claim | None: ...
    def list_claims(self, case_id: str) -> list[Claim]: ...
    def get_claim_evidence_links(self, claim_id: str) -> list[ClaimEvidenceLink]: ...
    def append_claim_evidence(self, claim_id: str, evidence: Sequence[Evidence], links: Sequence[ClaimEvidenceLink]) -> Claim: ...
    def save_follow_up_attempt(self, attempt: FollowUpResearchAttempt) -> FollowUpResearchAttempt: ...
    def list_follow_up_attempts(self, claim_id: str) -> list[FollowUpResearchAttempt]: ...
    def save_governance_decision(self, decision: GovernanceDecision) -> GovernanceDecision: ...
    def list_governance_decisions(self, target_id: str) -> list[GovernanceDecision]: ...
    def accept_checkpoint(self, run_id: str, stage: WorkflowStage, required_records: Sequence[tuple[str, str]]) -> None: ...
    def checkpoint_is_accepted(self, run_id: str, stage: WorkflowStage) -> bool: ...
    def latest_accepted_checkpoint(self, run_id: str) -> WorkflowStage | None: ...
